package com.woutwoot.svp;

import java.io.File;
import java.io.IOException;

public class Config {

	private static File plotsDir = new File(Main.folder + File.separator + "plots");

	public static void save() {
		saveSettings();
		savePlots();
	}

	public static void load() {
		loadSettings();
		loadPlots();
	}

	public static void saveSettings() {
		WootConfig file = new WootConfig(new File(Main.folder + File.separator + "config.properties"));
		file.setInteger("plotcount", Main.pm.plotCount);
		try {
			file.saveFile("SurvivalPlots config file.");
		} catch (IOException e) {
		}
	}

	public static void loadSettings() {
		File f = new File(Main.folder + File.separator + "config.properties");
		if (f.exists()) {
			WootConfig file = new WootConfig(f);
			try {
				file.loadFile();
			} catch (IOException e) {
				e.printStackTrace();
			}
			Main.pm.plotCount = file.getInteger("plotcount");
		}
	}

	public static void savePlots() {
		plotsDir.mkdirs();
		for (Plot p : Main.pm.plots) {
			WootConfig file = new WootConfig(new File(plotsDir + File.separator + p.getName() + ".plot"));
			file.setString("name", p.getName());
			file.setLocation("c1", p.getArea().getC1());
			file.setLocation("c2", p.getArea().getC2());
			file.setLocation("sign", p.getSignLocation());
			file.setStringList("friend", p.getFriends());
			file.setString("owner", p.getOwner());
			try {
				file.saveFile("Do not edit this file manually!");
			} catch (IOException e) {
				e.printStackTrace();
			}
		}
	}

	public static void loadPlots() {
		if(plotsDir.exists()){
			File[] list = plotsDir.listFiles();
			for (File file : list) {
				WootConfig conf = new WootConfig(file);
				try {
					conf.loadFile();
				} catch (IOException e) {
					e.printStackTrace();
				}
				Plot plot = new Plot(conf.getString("name"));
				plot.addFriends(conf.getStringList("friend"));
				plot.setOwner(conf.getString("owner"));
				plot.setSignLocation(conf.getLocation("sign"));
				plot.setArea(new Area(conf.getLocation("c1"), conf.getLocation("c2")));
				Main.pm.plots.add(plot);
			}
		}
	}

	public static void deletePlotFile(String plotname) {
		File file = new File(plotsDir + File.separator + plotname + ".plot");
		file.delete();
	}

}
